### ISSUE TITLE
Caused by android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by kartik0198** [nambicompany/expandable-fab#33]
Getting this crash on several devices. Using the latest library version. Please let me know if any further detail is needed.

Caused by android.content.res.Resources$NotFoundException
Resource ID #0x7f070113
android.content.res.ResourcesImpl.getValueForDensity (ResourcesImpl.java:225)
androidx.core.content.ContextCompat$Api21Impl.getDrawable (ContextCompat.java:862)
com.nambimobile.widgets.efab.ExpandableFab.setOptionalProperties (ExpandableFab.java:480)
androidx.core.content.ContextCompat.getDrawable (ContextCompat.java:480)
com.nambimobile.widgets.efab.ExpandableFab.<init> (ExpandableFab.java:73)
java.lang.reflect.Constructor.newInstance0 (Constructor.java)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:790)

**Comment by kabumere** [comment]
Hey @kartik0198,

1) Is this the full stack trace? If not, can you post the full stack trace?
2) Are you supporting different pixel densities with your icons/drawables for the ExpandableFab (`res/drawable`, `res/drawable-xhdpi`, etc)?
3) Are you supporting different screen sizes or orientations with your layouts (i.e. `res/layout-large`, `res/layout-land`, `res/layout-w600dp`, etc)?
4) Can I see how you're initializing your ExpandableFabLayout and its children (through XML or code)? Please use markdown for code blocks when posting it, so your code `looks like this` and is easier to read.

**Comment by kartik0198** [comment]
1. Here's the complete stack trace.
```
Fatal Exception: android.view.InflateException
Binary XML file line #158: Binary XML file line #36: Error inflating class com.nambimobile.widgets.efab.ExpandableFab

Caused by android.view.InflateException
Binary XML file line #36: Error inflating class com.nambimobile.widgets.efab.ExpandableFab

Caused by java.lang.reflect.InvocationTargetException
java.lang.reflect.Constructor.newInstance0 (Constructor.java)
androidx.databinding.DataBindingUtil.inflate (DataBindingUtil.java:95)
com.niyotail.consumer.ui.base.BaseFragment.onCreateView (BaseFragment.java:48)
androidx.fragment.app.Fragment.performCreateView (Fragment.java:2963)
androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:246)
com.niyotail.consumer.ui.main.MainActivity.onStart (MainActivity.java:331)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1391)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)

Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f070113
       at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
       at android.content.res.Resources.getDrawable(Resources.java:827)
       at android.content.Context.getDrawable(Context.java:635)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:862)
       at com.nambimobile.widgets.efab.ExpandableFab.setOptionalProperties(ExpandableFab.java:480)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:480)
       at com.nambimobile.widgets.efab.ExpandableFab.<init>(ExpandableFab.java:73)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
       at com.niyotail.consumer.ui.base.BaseFragment.onCreateView(BaseFragment.java:48)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at com.niyotail.consumer.ui.main.MainActivity.onStart(MainActivity.java:331)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
       at android.app.Activity.performStart(Activity.java:7165)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
2. Are you supporting different pixel densities with your icons/drawables for the ExpandableFab (res/drawable, res/drawable-xhdpi, etc)? No, we are not. 
3. Are you supporting different screen sizes or orientations with your layouts (i.e. res/layout-large, res/layout-land, res/layout-w600dp, etc)? No, we are not. 
4. Here's my XML file.
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

    </data>

    <com.nambimobile.widgets.efab.ExpandableFabLayout
        android:id="@+id/fab_layout_support"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.nambimobile.widgets.efab.Overlay
            android:id="@+id/fab_overlay"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:overlay_closingAnimationDurationMs="0"
            app:overlay_openingAnimationDurationMs="0" />

        <com.nambimobile.widgets.efab.ExpandableFab
            android:id="@+id/fab_support"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            android:layout_marginEnd="@dimen/space_lg"
            android:layout_marginBottom="42dp"
            app:efab_closingAnimationDurationMs="0"
            app:efab_color="@color/color_primary"
            app:efab_icon="@drawable/ic_support_button"
            app:efab_iconAnimationRotationDeg="0"
            app:efab_openingAnimationDurationMs="0"
            app:fab_color="@color/color_primary"
            app:label_backgroundColor="@color/color_primary"
            app:label_hiddenToVisibleAnimationDurationMs="0"
            app:label_visibleToHiddenAnimationDurationMs="0" />

        <com.nambimobile.widgets.efab.FabOption
            android:id="@+id/action_call"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:fab_closingAnimationDurationMs="100"
            app:fab_color="@color/color_primary"
            app:fab_icon="@drawable/ic_call"
            app:fab_openingAnimationDurationMs="100"
            app:label_backgroundColor="@color/color_primary"
            app:label_hiddenToVisibleAnimationDurationMs="100"
            app:label_text="@string/call_support"
            app:label_visibleToHiddenAnimationDurationMs="100" />


        <com.nambimobile.widgets.efab.FabOption
            android:id="@+id/action_feedback"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:fab_closingAnimationDurationMs="100"
            app:fab_color="@color/color_primary"
            app:fab_icon="@drawable/ic_thumbsup"
            app:fab_openingAnimationDurationMs="100"
            app:label_backgroundColor="@color/color_primary"
            app:label_hiddenToVisibleAnimationDurationMs="100"
            app:label_text="@string/feedback"
            app:label_visibleToHiddenAnimationDurationMs="100" />

        <com.nambimobile.widgets.efab.FabOption
            android:id="@+id/action_help"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:fab_closingAnimationDurationMs="100"
            app:fab_color="@color/color_primary"
            app:fab_icon="@drawable/ic_support_person"
            app:fab_openingAnimationDurationMs="100"
            app:label_backgroundColor="@color/color_primary"
            app:label_hiddenToVisibleAnimationDurationMs="100"
            app:label_text="Get help"
            app:label_visibleToHiddenAnimationDurationMs="100" />

    </com.nambimobile.widgets.efab.ExpandableFabLayout>
</layout>
```

**Comment by kabumere** [comment]
Hey @kartik0198.

From my review of the stack trace, it looks to me that a drawable being used for the ExpandableFab icon: 
- is in a density-specific folder that doesn't match the user's device's screen density (in other words, the drawable may be placed **only** in `res/drawable-xhdpi` while the Android framework is checking in `res/drawable-xxxhdpi` and `res/drawable` for a specific user's device, for example), or
- doesn't exist or isn't loaded by the time the ExpandableFab is being created

So my next questions to you are:
1) I know I asked this previously, but are you sure that the `ic_support_button` drawable that you're setting for `app:efab_icon` is actually in `res/drawable` and not in a density-specific folder (like `res/drawable-xhdpi`, `res/drawable-xxxhdpi`, etc)? Can you double check?
    1.a) Is `ic_support_button` an icon you created and you're 100% sure it's not in a density-specific folder, or is it a drawable you're accessing from a 3rd party library or framework?
2) The library defaults to setting ExpandableFab's icon to a drawable called `ic_plus_white_24dp` (a white plus sign) before trying to apply the drawable a developer sets in their own project. Is it possible that you also have a drawable called `ic_plus_white_24dp` that is in a density-specific folder (and may be overriding the drawable in the library)?

Let me know if neither of the above apply to your app. If they do not, then I wonder if either the library's default icon (`ic_plus_white_24dp`), or your icon (`ic_support_button`), is somehow not being loaded in time, or is missing from the APK the user has installed. Are you publishing your app to Google Play using the new App Bundle format (.aab instead of .apk)? If so, I wonder if it's being smarter than it should be and is not installing all the resources the user's device needs at install time (though this would hopefully be unlikely).

**Comment by kabumere** [comment]
Hey @kartik0198,

Any update?

**Comment by kabumere** [comment]
Hey @kartik0198,

Your setup looks correct. I have not been able to reproduce the issue on an Android Pie (aka '9') physical device, or on an Android Oreo (aka '8.x') emulator. I'm assuming you haven't been able to reproduce it either, though if you have, please let me know which steps you took to reproduce the issue.

My best guess at the moment is that this stems from using the new .aab App Bundle format. I think we're hitting one of these two cases:

1. User 1 downloads the app from the Play Store. Google provides an install specific to their device configuration. User 1 allows the APK of your app to be published to a third-party store for sideloadable APKs where User 2 downloads it from. User 2's device configuration is different from User 1, so the sideloaded APK does not function as expected on their own device.
2. Or maybe (though less likely): the APKs Google is generating from the app bundle you provided are somehow not including the proper resources users need (especially if this button only exists in a dynamic feature that a user is suppose to download after install).

There are ways to check programmatically if your app is being sideloaded. Barring that however, I can't reproduce the issue so it's tough to find a proper solution.

**Comment by kabumere** [comment]
Hey @kartik0198,

v1.2.0 of the library was just published. The bug I described above is fixed in this version. If you choose to use it, let me know if it solves the issue some of your users were experiencing. If it doesn't, I'd be glad to do further research into the problem.

**Comment by kartik0198** [comment]
Thanks, I am releasing a new build with the updated library. Will let you know if there is a regression.

**Comment by kartik0198** [comment]
Hi @kabumere , i am still getting this crash on the latest version i.e v1.2.1. 

```
Caused by android.content.res.Resources$NotFoundException
Resource ID #0x7f07011a
android.content.res.ResourcesImpl.getValue (ResourcesImpl.java:190)
androidx.appcompat.content.res.AppCompatResources.getDrawable (AppCompatResources.java:104)
com.nambimobile.widgets.efab.ExpandableFab.<init> (ExpandableFab.java:76)
java.lang.reflect.Constructor.newInstance0 (Constructor.java)
androidx.databinding.DataBindingUtil.inflate (DataBindingUtil.java:95)
com.niyotail.consumer.ui.base.BaseFragment.onCreateView (BaseFragment.java:48)
androidx.fragment.app.Fragment.performCreateView (Fragment.java:2963)
androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:246)
com.niyotail.consumer.ui.main.MainActivity.onStart (MainActivity.java:331)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1248)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:780)
```
Crash stats: 
75%  crashes on - Android 9
13%- Android 7
12%- Android 8

**Comment by kabumere** [comment]
Hey @kartik0198,

Are you able to reproduce the crash on your end? If so, can you post the steps to reproduce? I can't reproduce that bug.

**Comment by kartik0198** [comment]
Nope, i am not able to reproduce this crash but its crashing heavily, most frequent crash now in the latest version. :( also most of the crashes are in android 7

**Comment by kabumere** [comment]
From all your stack traces, the issue is occurring when trying to set an icon on the main ExpandableFab button ([here specifically](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/ExpandableFab.kt#L76)). We use to use `ContextCompat` instead of `AppCompatResources`, but even the old way still caused issues to some of your users.

I can't reproduce the crash, and it sounds like you can't reproduce the crash either. So without steps on how to reproduce it so I can solve it, we're kind of flying in the dark here at this point. I'm surprised you're getting the crash so frequently, as this seems like an edge case (since I haven't been hearing anyone else encounter this issue).

Is the crash happening frequently *to the same users*? Or is it happening frequently to unique users every time?

You could try giving me more data so I can try to more accurately mimic the environment your users are installing from, but I can't guarantee that it'll help without definitive steps to reproduce.

1. What Android versions is this affecting (is only *only* Android 7, or is Android 7 the biggest share, but it's still happening to 8, 9, 10, etc)?
2. What device models is this affecting (Samsung S series? Google Pixels? Huawei?)?
3. What are the top user regions that are getting affected (US? India? South Korea?)?
4. Do you know if your app is being sideloaded, instead of being installed directly from the Google Play Store? 
    - this could create issues with resources, especially with the new app bundle format that Google uses to generate APKs specific to a user's device configuration
5. Do you have something like `vectorDrawables.useSupportLibrary = true` defined in your build.gradle? Are there any other related properties you've added to your build.gradle?

**Comment by kartik0198** [comment]
What Android versions is this affecting (is only only Android 7, or is Android 7 the biggest share, but it's still happening to 8, 9, 10, etc)? - 
Android 7
17%
Android 9
3%
Android 8

What device models is this affecting (Samsung S series? Google Pixels? Huawei?)? - 47%
OnePlus
32%
samsung
17%
Google

What are the top user regions that are getting affected (US? India? South Korea?)? - users are from india only as the app is used in india only.
Do you know if your app is being sideloaded, instead of being installed directly from the Google Play Store? - can't say, although i also think that this issue is being caused only when the app is sideloaded (its e-com app so people may/do sideload for referral benefits)
this could create issues with resources, especially with the new app bundle format that Google uses to generate APKs specific to a user's device configuration
Do you have something like vectorDrawables.useSupportLibrary = true defined in your build.gradle? Are there any other related properties you've added to your build.gradle? - no i dont have this property defined in my gradle

**Comment by kabumere** [comment]
@kartik0198,

That's surprising. When I try to use your `ic_support_button` drawable from above, I get the following error when building:

```
Caused by: org.gradle.api.GradleException: Can't process attribute android:fillColor="@color/white": references to other resources are not supported by build-time PNG generation.
File was preprocessed as vector drawable support was added in Android 5.0 (API level 21)
See http://developer.android.com/tools/help/vector-asset-studio.html for details.
	at com.android.build.gradle.tasks.MergeResources$MergeResourcesVectorDrawableRenderer.generateFile(MergeResources.java:440)
	at com.android.ide.common.resources.MergedResourceWriter$FileGenerationWorkAction.run(MergedResourceWriter.java:412)
	... 31 more
```

It's because your vector drawable references other resources inside of it (e.g.: you use `android:fillColor="@color/white"` which references a color resource, instead of just using `android:fillColor="#FFFFFF"`. 

I have been following [this Stack Overflow answer](https://stackoverflow.com/a/47132142/14032472) and including `vectorDrawables.useSupportLibrary = true` in my build.gradle in order to get the error to go away and build.

If you're not setting `vectorDrawables.useSupportLibrary = true` in your build.gradle though, how did you avoid that error? Or is your minSDK >= 24?

If your minSDK is less than 24, you should be getting this error too. Maybe the solution you used is leading to the issue and that's why I haven't been able to replicate it? Do you mind posting your build.gradle?

**Comment by kartik0198** [comment]
That's strange, my minsdk is set at 21 but still i am not getting any gradle errors. In any case, i have changed the fill color to absolute value instead of referencing to a color resource (android:fillColor="#FFFFFF").
Here's my gradle file - 

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'dagger.hilt.android.plugin'
apply plugin: 'com.google.firebase.firebase-perf'

apply from: '../ktlint.gradle'

android {

    def versionMajor = 2
    def versionMinor = 5
    def versionPatch = 2
    def releaseNumber = 98
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "(hidden)"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 30000 + releaseNumber
        versionName "${versionMajor}.${versionMinor}.${versionPatch}"
        buildConfigField "int", "RELEASE_NUMBER", "$releaseNumber"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        debug {
            storeFile file('../keystore/debug.keystore')
            storePassword "(hidden)"
            keyAlias "(hidden)"
            keyPassword "(hidden)"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            debuggable true
            minifyEnabled false
            firebaseCrashlytics { mappingFileUploadEnabled false }
            buildConfigField "String", "API_ENDPOINT", "(hidden)"
            applicationIdSuffix ".d"
            versionNameSuffix "-d"
            resValue "string", "app_name", "(hidden)"
        }
        release {
            debuggable false
            minifyEnabled true
            firebaseCrashlytics { mappingFileUploadEnabled true }
            shrinkResources true
            buildConfigField "String", "API_ENDPOINT", "(hidden)"
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            resValue "string", "app_name", "(hidden)"
        }
    }

    android.applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "(hidden)-v${variant.versionName}(${variant.versionCode})-${variant.buildType.name}.apk"
        }
    }

    buildTypes.each {
        it.buildConfigField "String", "MIXPANEL_API_KEY", mixpanelApiKey
    }

    compileOptions {
        sourceCompatibility rootProject.ext.javaVersion
        targetCompatibility rootProject.ext.javaVersion
    }

    kotlinOptions {
        jvmTarget = rootProject.ext.javaVersion.toString()
    }

    buildFeatures {
        dataBinding true
    }

    bundle {
        language {
            /* Specifies that the app bundle should not support configuration APKs for language resources. These
               resources are instead packaged with each base and dynamic feature APK. */
            enableSplit = false
        }
    }
}

dependencies {
    //implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    /* PLEASE KEEP THE DEPENDENCIES BLOCK CLEAN BY ADDING NEW LIBRARIES AS PER THE CATEGORY ONLY !! */

    def retrofit_version = '2.9.0'
    def room_version = "2.3.0"

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    //Modules
    implementation project(path: ':analytics')
    implementation project(path: ':barcode')
    implementation project(path: ':core')
    implementation project(path: ':commons:utils')
    implementation project(path: ':commons:ui')
    implementation project(path: ':commons:views')

    //Kotlin
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.5.2-native-mt'

    //AndroidX
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.1'
    implementation 'androidx.activity:activity-ktx:1.4.0'
    implementation "androidx.fragment:fragment-ktx:1.3.6"
    implementation "androidx.recyclerview:recyclerview:1.2.1"

    //Jetpack Components
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0'
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.4.0"
    implementation "androidx.navigation:navigation-fragment-ktx:2.3.5"
    implementation "androidx.navigation:navigation-ui-ktx:2.3.5"
    implementation "androidx.paging:paging-runtime-ktx:3.0.1"
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"

    //Firebase
    implementation platform('com.google.firebase:firebase-bom:28.4.2')
    implementation 'com.google.firebase:firebase-config-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-appindexing'
    implementation 'com.google.firebase:firebase-inappmessaging-display-ktx'
    implementation 'com.google.firebase:firebase-firestore-ktx'
    implementation 'com.google.firebase:firebase-perf-ktx'
    implementation 'com.google.firebase:firebase-storage-ktx'
    implementation("com.google.firebase:firebase-iid") { because("github.com/mixpanel/mixpanel-android/issues/744") }

    //Google play services
    implementation 'com.google.android.play:core-ktx:1.8.1'
    implementation "com.google.android.gms:play-services-maps:18.0.0"
    implementation "com.google.android.gms:play-services-location:18.0.0"
    implementation 'com.google.android.gms:play-services-auth:19.2.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:17.5.1'
    implementation 'com.google.android.gms:play-services-ads-identifier:17.1.0'
    implementation 'com.android.installreferrer:installreferrer:2.2'

    //Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    //Networking
    implementation(platform("com.squareup.okhttp3:okhttp-bom:4.9.1"))
    implementation("com.squareup.okhttp3:okhttp")
    implementation("com.squareup.okhttp3:logging-interceptor")
    implementation "com.squareup.retrofit2:retrofit:${retrofit_version}"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"

    //Debugging
    implementation 'com.facebook.stetho:stetho:1.6.0'
    implementation 'com.facebook.stetho:stetho-okhttp3:1.6.0'
    implementation 'com.jakewharton.timber:timber:5.0.1'
    // debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.7'
    debugImplementation 'com.mocklets:pluto:1.1.1'
    releaseImplementation 'com.mocklets:pluto-no-op:1.1.1'

    //Payments
    implementation 'com.razorpay:checkout:1.6.12'

    //UI
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'com.airbnb.android:lottie:4.2.0'
    implementation 'com.github.GrenderG:Toasty:1.5.0'
    implementation 'com.github.cachapa:ExpandableLayout:2.9.2'
    implementation 'com.robinhood.ticker:ticker:2.0.3'
    implementation 'com.nambimobile.widgets:expandable-fab:1.2.1'
    implementation 'com.github.Jamshid-M:IGRefreshLayout:1.0.3'

    //Custom
    implementation 'com.github.skydoves:preferenceroom:1.2.2'
    kapt 'com.github.skydoves:preferenceroom-processor:1.2.2'
    implementation 'io.branch.sdk.android:library:5.0.14'
    implementation 'io.coil-kt:coil:1.3.2'
    implementation("io.coil-kt:coil-gif:1.3.2")
    implementation "com.truecaller.android.sdk:truecaller-sdk:2.6.0"
    implementation 'com.webengage:android-sdk:3.18.7'

    //Dagger-Hilt
    implementation "com.google.dagger:hilt-android:$hilt_version"
    kapt "com.google.dagger:hilt-compiler:$hilt_version"

}
apply plugin: 'com.google.gms.google-services'

check.dependsOn ktlint
 
```

**Comment by kabumere** [comment]
@kartik0198,

There's nothing in your build.gradle that jumps out at me as being suspect. At this point, I'm not sure there's anything else I can do. You can't reproduce the issue, and neither can I.

I just built signed release versions of a proguarded test app that included the library, and tested on Android 19 and 21 (emulator), and Androids 28, 29 and 30 (physical devices), and it worked without issue every time.

My final suspicions on this are:
1. Some of your users are sideloading your app, and the particular APK configuration they're downloading is not meant for their specific device and it's causing issues. I believe this is especially an issue when publishing using App Bundles, since Google uses that bundle info to provide users with an APK specific to their general device configuration. 
    - Example: if User 'A' downloads a specific APK configuration for their device from the Play Store, then that APK ends up on a sideloading website, User 'B' might encounter issues when installing it since their device may not fully support that APK configuration.
2. If you're using Android Studio 3.0 or higher, Android Gradle plugin 3.0 or higher, and have a minSDK of less than 24, you *should* have had to include `vectorDrawables.useSupportLibrary = true` when using drawables that referenced other resources like colors. Some how you got around that without seeing an error when you were testing, but perhaps that led to a deeper problem with your vector drawables? You can try removing all references to resources from all your drawables and see if that helps.

Other than that, I'm out of ideas. Sorry this issue couldn't be resolved :slightly_frowning_face:

**EDIT**: Some Stack Overflow posts that support my suspicion with number 1 above:
https://stackoverflow.com/q/52469914/14032472
https://stackoverflow.com/a/52474885/14032472
https://stackoverflow.com/a/59514472/14032472
https://stackoverflow.com/q/65167556/14032472

**Comment by kartik0198** [comment]
Yes, I have worked on point 2. Hoping that it fixes the issue although I also think some users who have side-loaded the apk are affected and they might be trying again and again to open the app.
Anyway, thanks a lot for your help!

**Comment by kabumere** [comment]
No problem @kartik0198! Keep me posted if you find out any more information about those crashes or you become able to reproduce them, and we can revisit and reopen this ticket for further testing.
